version: '3.8'

services:
  ml-classifier:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./models:/app/models:ro
      - ./app:/app/app:ro
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s